(()=>{"use strict";
const $=id=>document.getElementById(id);let auth=null,view="live",items=[],categories=[],activeCat="all";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function base(){return auth.server.replace(/\/$/,"")}
function api(action,extra=""){return base()+"/player_api.php?username="+encodeURIComponent(auth.username)+"&password="+encodeURIComponent(auth.password)+(action?"&action="+action:"")+extra}
async function get(url){const r=await fetch(url);if(!r.ok)throw Error("HTTP "+r.status);return r.json()}
function save(){localStorage.setItem("sb.webos.auth",JSON.stringify(auth))}
function focusFirst(){setTimeout(()=>document.querySelector(".focusable:not(.hidden),.card,.cat")?.focus(),20)}
async function signin(){const server=$("server").value.trim(),username=$("username").value.trim(),password=$("password").value;if(!server||!username||!password)return fail("Enter your server, username and password.");auth={server:/^https?:\/\//i.test(server)?server:"http://"+server,username,password};$("signin").disabled=true;$("status").textContent="Connecting…";try{const data=await get(api(""));if(!data.user_info||String(data.user_info.auth)!=="1")throw Error("Login rejected");save();showHome();await loadView("live")}catch(e){fail("Could not sign in: "+e.message);auth=null}$("signin").disabled=false;$("status").textContent=""}
function fail(s){$("error").textContent=s}
function showHome(){$("login").classList.add("hidden");$("home").classList.remove("hidden")}
async function loadView(v){view=v;activeCat="all";$("heading").textContent=v==="live"?"Live TV":v==="movies"?"Movies":"Series";document.querySelectorAll(".nav[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));$("grid").innerHTML="<p>Loading…</p>";try{const ca=v==="live"?"get_live_categories":v==="movies"?"get_vod_categories":"get_series_categories";const ia=v==="live"?"get_live_streams":v==="movies"?"get_vod_streams":"get_series";[categories,items]=await Promise.all([get(api(ca)),get(api(ia))]);renderCats();render()}catch(e){$("grid").innerHTML="<p>Unable to load: "+esc(e.message)+"</p>"}}
function renderCats(){$("categories").innerHTML='<button class="cat focusable active" data-cat="all">All</button>'+categories.map(c=>'<button class="cat focusable" data-cat="'+esc(c.category_id)+'">'+esc(c.category_name)+'</button>').join("")}
function render(){const q=$("search").value.trim().toLowerCase();const f=items.filter(x=>(activeCat==="all"||String(x.category_id)===activeCat)&&String(x.name??x.title??"").toLowerCase().includes(q));$("grid").innerHTML=f.slice(0,1200).map((x,i)=>{const name=x.name??x.title??"Untitled",img=x.stream_icon??x.cover??"";return '<button class="card focusable" data-i="'+items.indexOf(x)+'">'+(img?'<img src="'+esc(img)+'" onerror="this.style.display=\'none\'">':"")+'<strong>'+esc(name)+'</strong><small>'+esc(view==="live"?"Live":view==="movies"?"Movie":"Series")+'</small></button>'}).join("")||"<p>No results.</p>"}
function play(x){if(view==="series"){return loadSeries(x)}const ext=view==="live"?"ts":(x.container_extension||"mp4"),id=view==="live"?x.stream_id:x.stream_id,url=base()+"/"+(view==="live"?"live":"movie")+"/"+encodeURIComponent(auth.username)+"/"+encodeURIComponent(auth.password)+"/"+id+"."+ext;openVideo(url,x.name??x.title)}
async function loadSeries(x){$("grid").innerHTML="<p>Loading episodes…</p>";try{const d=await get(api("get_series_info","&series_id="+encodeURIComponent(x.series_id)));const eps=Object.values(d.episodes||{}).flat();$("grid").innerHTML=eps.map((e,i)=>'<button class="card focusable" data-episode="'+i+'"><strong>'+esc(e.title||("Episode "+e.episode_num))+'</strong><small>S'+esc(e.season||"")+" E"+esc(e.episode_num||"")+'</small></button>').join("");$("grid").onclick=ev=>{const b=ev.target.closest("[data-episode]");if(!b)return;const e=eps[+b.dataset.episode],ext=e.container_extension||"mp4";openVideo(base()+"/series/"+encodeURIComponent(auth.username)+"/"+encodeURIComponent(auth.password)+"/"+e.id+"."+ext,e.title)}}catch(e){$("grid").innerHTML="<p>Unable to load series.</p>"}}
function openVideo(url,title){$("player").classList.remove("hidden");$("playingTitle").textContent=title||"";$("video").src=url;$("video").play().catch(()=>{});$("back").focus()}
function closeVideo(){$("video").pause();$("video").removeAttribute("src");$("video").load();$("player").classList.add("hidden");focusFirst()}
document.addEventListener("click",e=>{const nav=e.target.closest("[data-view]");if(nav)return loadView(nav.dataset.view);const cat=e.target.closest("[data-cat]");if(cat){activeCat=cat.dataset.cat;document.querySelectorAll(".cat").forEach(x=>x.classList.toggle("active",x===cat));return render()}const card=e.target.closest("[data-i]");if(card)return play(items[+card.dataset.i])});
document.addEventListener("keydown",e=>{if(e.key==="Backspace"||e.key==="Escape"||e.keyCode===461){if(!$("player").classList.contains("hidden")){e.preventDefault();closeVideo();return}if(view!=="live"){e.preventDefault();loadView("live")}}});
$("signin").onclick=signin;$("search").oninput=render;$("back").onclick=closeVideo;$("logout").onclick=()=>{localStorage.removeItem("sb.webos.auth");location.reload()};
try{const s=JSON.parse(localStorage.getItem("sb.webos.auth")||"null");if(s){auth=s;showHome();loadView("live")}else $("server").focus()}catch(_){$("server").focus()}
})();